# Generated by Django 5.2.6 on 2025-10-18 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='title',
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
